name: Doppler GitHub Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build binaries
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v4

      - name: Set env vars
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Cargo build
        uses: dtolnay/rust-toolchain@stable
        run: cargo build --release

      - name: Cargo test
        run: cargo test --all-features

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          name: doppler ${{ env.RELEASE_VERSION }}
          draft: true
          files: |
            LICENSE
            README.md
            doppler_files
            target/release/doppler
            target/release/parsetest
          body: |
            # doppler ${{ env.RELEASE_VERSION }}

            TODO add common release notes in this template

            ```
            sample code block
            ```
